Restaurant.create(name: 'MacDO', address: "rue du loup", phone_number: "0650556192", category: 'chinese')
Restaurant.create(name: 'BK', address: "rue du mouton", phone_number: "0650556132", category: 'italian')
Restaurant.create(name: 'KFC', address: "rue du chat", phone_number: "0650556191", category: 'japanese')
Restaurant.create(name: 'subway', address: "rue du loup", phone_number: "0650556192", category: 'french')
Restaurant.create(name: 'eatsalade', address: "rue du loup", phone_number: "0650556192", category: 'belgian')
